[project]
name = "simple-redstone"
version = "0.1.1"
description = "A simple, pure ASCII format to encode Minecraft redstone structures"
readme = "README.md"
authors = [
    { name = "MqCreaple", email = "gmq14159@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "glfw>=2.10.2",
    "gltflib>=1.0.13",
    "imageio>=2.37.4",
    "minecraft-data>=3.20.0",
    "nucleation>=0.10.24",
    "numpy>=2.0",
    "pillow>=12.3.0",
    "pygfx>=0.17.0",
    "pyyaml>=6.0.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

[project.scripts]
simple-redstone = "simple_redstone:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
